Lm 384] fix two bugs on lemonfrog.ch website
lemonfrog/lemonfrog.github.io pull request #2
Opened 2021-07-11 16:15 UTC by bobilo-qa

This PR adds a bunch of device breakpoints, new logo, furthermore improve the text in de and en version (thanks to Charlotte for helping). I've also changed the structure of our css files to follow the advice of Mateusz. Now there are 3 files. The separated file 'normalize.css' with no changes and 2 new each per language with my declarations for mobiles. 

Don't know why there is now a new file .DS_Store because I have not added him. Must jump in during the commit.

2021-07-11 16:18 UTC, mateuszgorniak commented
Please create `.gitignore` file and add `.DS_Store` as one of the excluded files - https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

2021-07-11 16:20 UTC, mateuszgorniak commented on css/styles_en.css
> +/*! normalize.css v7.0.0 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,footer,header,nav
Do we have to copy the same content everywhere?

2021-07-12 10:10 UTC, mateuszgorniak requested changes

2021-07-12 10:10 UTC, mateuszgorniak commented on css/styles_en.css
> +@media only screen and (min-width: 800px)
You can work on indentations, use 2 spaces (1 tab) and group classes by the same parent node, like:
```
@media only screen and (min-width: 800px)
                   and (max-width: 1000px)
                   and (orientation: landscape) {
  .header-main__title {
     padding-top: 20px;
     margin-top: 46px;
  }
  .header-main__text {
    margin-bottom: 30px;
  }
}
```

2021-07-12 10:10 UTC, mateuszgorniak commented on css/styles_en.css
> +/*! normalize.css v7.0.0 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,footer,header,nav
As we discussed on Slack, please use separate `normalize.css` file and just add it to the main page `<link rel="stylesheet" href="css/normalize.css" type="text/css" media="all" />` to include the code.

2021-07-13 22:05 UTC, bobilo-qa reviewed
Didn't change the commit message but yeah hope now it's better 😉

2021-07-14 06:51 UTC, mateuszgorniak requested changes
Please check spacing and remove `images/.DS_Store` from the repository.

2021-07-14 06:51 UTC, mateuszgorniak commented on css/styles.css
> +                   and (orientation: portrait)  {
Try to keep consistency with spacings - here you used one, `.header-main__text{` no spacing between class name and `{`, and below you use `.header-main__title {`

2021-07-14 06:51 UTC, mateuszgorniak commented on en/index.html
> +    <link rel="stylesheet" href="../css/normalize.css" type="text/css" media="all" />
👍

2021-07-14 07:50 UTC, mateuszgorniak approved these changes

2021-07-15 09:25 UTC, lemonfrog approved these changes

2021-07-15 09:28 UTC, merged